BettingGameApp/models/models.py
from BettingGameApp import db, login_manager
from flask_login import UserMixin
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    register_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow())
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    is_admin = db.Column(db.Integer, nullable=False, default=1)
    account_address = db.Column(db.String(60), nullable=False )
    keystore = db.Column(db.Text, nullable=False)
    secret = db.Column(db.String(60), nullable=True)

    def __repr__(self):
        return f"<USER: {self.id}, {self.username}, {self.register_date}, {'admin' if self.is_admin else 'not admin'}>"

class Activity(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    request_type = db.Column(db.Integer, nullable=False)
    log_datetime = db.Column(db.DateTime, nullable=False, default=datetime.utcnow())
    is_success = db.Column(db.Integer, unique=False, nullable=False)
    channel = db.Column(db.String(30), nullable=False) # either api or web

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    activity = db.relationship('User',
                               backref=db.backref('activity_log', lazy=True))

BettingGameApp/main/forms.py
from BettingGameApp.w3.BettingGameContract import BettingGameContract

from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, IntegerField, FloatField)
from wtforms.validators import DataRequired, InputRequired, ValidationError
from BettingGameApp.w3.Connection import Rinkeby_Connection

w3 = Rinkeby_Connection.w3
bgc = BettingGameContract().contract()


def is_valid_gameID(form, field):
    message = 'This is not a valid Game ID'

    current_game_count = bgc.functions.numberOfGames().call()
    if int(field.data) <= int(current_game_count):
        return True

    else:
        raise ValidationError(message)


def has_available_bal(form, field):
    message = 'There are insufficient funds to support transaction.'

    account = current_user.account_address
    current_account_bal = w3.eth.get_balance(account)
    bet_amount_wei = w3.toWei(field.data, 'ether')

    if bet_amount_wei < current_account_bal:
        return True

    else:
        raise ValidationError(message)


class BetForm(FlaskForm):
    message = "Data input required"

    game_id = IntegerField('Game ID', validators=[
        InputRequired(message), is_valid_gameID
    ])

    prediction = IntegerField('Prediction', validators=[
        InputRequired(message),
    ])

    bet_amount = FloatField('Bet Amount', validators=[
        InputRequired(message), has_available_bal
    ])

BettingGameApp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, PasswordField, SubmitField, FloatField)
from wtforms.validators import DataRequired, EqualTo, InputRequired
from BettingGameApp.users.validators import validate_email, validate_password, validate_username

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[
        DataRequired(), validate_email
    ])

    password = PasswordField('Password', validators=[
        DataRequired()
    ])

    login = SubmitField('Login')


class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[
        DataRequired(), validate_email
    ])
    username = StringField('Username', validators=[
        DataRequired(), validate_username
    ])
    password = PasswordField('Password', validators=[
        EqualTo('password', message='Passwords must match'),
        validate_password
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        InputRequired()
    ])

BettingGameApp/__init__.py
import os
from flask import Flask, Blueprint
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_restful import Api
# from flask_jwt import JWT
from web3 import Web3

from BettingGameApp.config import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'warning'

# Web3
NODE_URL = ''
w3 = ''


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)
    api = Api(app)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    @app.before_first_request
    def create_tables():
        db.create_all()

    # api blueprints
    from BettingGameApp.resources.users import user_api

    app.register_blueprint(user_api)


    from BettingGameApp.users.routes import users
    from BettingGameApp.main.routes import main
    # route blueprints
    app.register_blueprint(users)
    app.register_blueprint(main)


    from BettingGameApp.resources.users import Login

    api.add_resource(Login, '/api/login')

    return app

BettingGameApp/main/routes.py
import os

from flask import (flash, render_template, redirect, url_for, Blueprint)
from flask_login import current_user, login_required

from BettingGameApp.main.forms import BetForm
from BettingGameApp.main.utils import GameDetails, BetData, Bet
from eth_account import Account

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
@login_required
def home():
    gd = GameDetails()
    gd.get_all_games()
    all_games = gd.all_games
    return render_template("home.html", game_data=all_games)


@main.route('/place_bet/<int:game_id>', methods=['GET', 'POST'])
@login_required
def place_bet(game_id):
    form = BetForm(game_id=game_id)

    game_data = GameDetails().get_single_game(game_id)

    bd = BetData(game_id)
    bd.get_bet_data(limit_data=True)

    if form.validate_on_submit():
        # key = Account.decrypt(current_user.keystore, os.environ.get('TEST_PASSWORD'))
        account = Account.from_key(current_user.keystore)
        bet = Bet(game_id=form.game_id.data, prediction=form.prediction.data, bet_amount=form.bet_amount.data)
        bet.place_bet(account)

        if bet.success:
            data = bet.get_event_details()
            message = f"Bet placed: GAME_ID {data['game_id']}; BET MAKER {data['betMaker']}; BET AMOUNT {data['betAmount']}"
            flash(message, 'success')

        elif not bet.success:
            message = f"BET FAILURE: {bet.error_message}"
            flash(message, 'warning')

        else:
            message = "Something went wrong."
            flash(message, 'danger')

    return render_template("place_bet.html", form=form, bet_data=bd.bet_data, game_data=game_data)

BettingGameApp/users/routes.py
from flask import (Blueprint, render_template, redirect,
                   url_for, flash)
from flask_login import current_user, login_required
from BettingGameApp import bcrypt
from BettingGameApp.users.forms import LoginForm, RegisterForm
from BettingGameApp.users.utils import register_user, login_user_decrypt, logout_user_encrypt, UserProfile
from BettingGameApp.models.models import User

users = Blueprint('users', __name__)


@users.route("/profile", methods=["GET"])
@login_required
def profile():
    user = UserProfile.get_data(current_user.account_address)

    return render_template("profile.html", user=user)

@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # ACTIVITY LOG
            login_user_decrypt(user, form.password.data)
            flash(f'Welcome back, {user.username}', 'success')
            return redirect(url_for('main.home'))

        else:
            flash(f'Unsuccessful login attempt.', 'warning')
    return render_template("login.html", form=form)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegisterForm()
    if form.validate_on_submit():
        user = register_user(form)
        if user:
            # ACTIVITY LOG
            flash("You have been successfully registered", "success")
            return redirect(url_for('users.login'))

        else:
            flash("Something went wrong, please try again.", "warning")

    return render_template('register.html', form=form)


@users.route("/logout", methods=["GET"])
def logout():
    logout_user_encrypt(current_user)
    return redirect(url_for('users.login'))

BettingGameApp/templates/home.html
{% extends "layout.html" %}
{% block content %}
<h1>HOME PAGE</h1>

<div class="row justify-content-center">
    <div class="col-8">
        <table class="table table-hover shadow">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Status</th>
                    <th scope="col">Open Date</th>
                    <th scope="col">Total Pool</th>
                    <th scope="col">See More</th>
                </tr>
            </thead>
            <tbody>
                {% if game_data %}
                    {% for g in game_data %}
                    <tr>
                        <th scope="row">{{ g['id'] }}</th>
                        <td>{{ g['status'] }}</td>
                        <td>{{ g['create_time'] }}</td>
                        <td>{{ g['total_pool'] }}</td>
                        <td><div type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#game_ID_{{ g['id'] }}">Click Here</div></td>
                    </tr>

                    <div class="modal fade" id="game_ID_{{ g['id'] }}" tabindex="-1" aria-labelledby="game_ID_{{ g['id'] }}Label" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="game_ID_{{ g['id'] }}Label">Game {{ g['id'] }} Data</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="container-fluid">
                                        <div class="row justify-content-start">
                                            <div class="col-4">
                                                <h6>Manager</h6>
                                            </div>
                                            <div class="col-2">
                                                <span class="badge bg-secondary">
                                                    <i class="fas fa-arrow-circle-right"></i>
                                                </span>
                                            </div>
                                            <div class="col-6">
                                                <h6 class="text-truncate" data-bs-toggle="popover" data-bs-trigger="hover focus" title="Manager Address" data-bs-content="{{ g['manager'] }}">
                                                    {{ g['manager'] }}
                                                </h6>
                                            </div>
                                        </div>
                                        <div class="row justify-content-start">
                                            <div class="col-4">
                                                <h6>Status</h6>
                                            </div>
                                            <div class="col-2">
                                                <span class="badge bg-secondary">
                                                    <i class="fas fa-arrow-circle-right"></i>
                                                </span>
                                            </div>
                                            <div class="col-6">
                                                <h6>{{ g['status'] }}</h6>
                                            </div>
                                        </div>
                                        <div class="row justify-content-start">
                                            <div class="col-4">
                                                <h6>Open Since</h6>
                                            </div>
                                            <div class="col-2">
                                                <span class="badge bg-secondary">
                                                    <i class="fas fa-arrow-circle-right"></i>
                                                </span>
                                            </div>
                                            <div class="col-6">
                                                <h6>{{ g['create_time'] }}</h6>
                                            </div>
                                        </div>
                                        <div class="row justify-content-start">
                                            <div class="col-4">
                                                <h6>Bet Minimum</h6>
                                            </div>
                                            <div class="col-2">
                                                <span class="badge bg-secondary">
                                                    <i class="fas fa-arrow-circle-right"></i>
                                                </span>
                                            </div>
                                            <div class="col-6">
                                                <h6>{{ g['bet_min'] }} <i class="fab fa-ethereum"></i></h6>
                                            </div>
                                        </div>
                                        <div class="row justify-content-start">
                                            <div class="col-4">
                                                <h6>Bet Range</h6>
                                            </div>
                                            <div class="col-2">
                                                <span class="badge bg-secondary">
                                                    <i class="fas fa-arrow-circle-right"></i>
                                                </span>
                                            </div>
                                            <div class="col-6">
                                                <h6>0 - {{ g['val_range'] }}</h6>
                                            </div>
                                        </div>
                                        <div class="row justify-content-start">
                                            <div class="col-4">
                                                <h6>Total Pool</h6>
                                            </div>
                                            <div class="col-2">
                                                <span class="badge bg-secondary">
                                                    <i class="fas fa-arrow-circle-right"></i>
                                                </span>
                                            </div>
                                            <div class="col-6">
                                                <h6 class="text-truncate">{{ g['total_pool'] }} <i class="fab fa-ethereum"></i></h6>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a class="btn btn-primary" href="{{ url_for('main.place_bet', game_id=g['id']) }}">Place Bet</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                    <tr>
                        <th scope="row">0</th>
                        <td colspan="4"> NO DATA AVAILABLE</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>


{% endblock content %}

BettingGameApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!-- My CSS -->
    <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">

    <title>Blockchain Game</title>
</head>
<body>
<!-- This is to hide nav bar from reg & login page -->
{% if current_user.is_authenticated %}
<div class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand mb-0 h1 px-2" href="{{ url_for('main.home') }}">
                ChainGamble <i class="fas fa-dice"></i>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#menu" aria-controls="menu" aria-expanded="false" aria-label="Show Menu">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</div>
<div class="collapse" id="menu">
    <div class="bg-dark p-4">
        <h6>
            <a class="nav-link text-white h4" href="#">Profile</a>
        </h6>
        <h6>
            <a class="nav-link text-white h4" href="#">Manage Game</a>
        </h6>
        <h6>
            <a class="nav-link text-white h4" href="{{ url_for('users.logout') }}">Logout</a>
        </h6>
    </div>
</div>
{% endif %}
<!-- Alerts -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

{% block content %}
<!-- Page Content -->
{% endblock content %}

<!-- Bootstrap Bundle with Popper-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<!-- Font Awesome Install -->
<script src="https://kit.fontawesome.com/9696a88616.js" crossorigin="anonymous"></script>
<!-- for Popovers -->
<script>
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
    return new bootstrap.Popover(popoverTriggerEl)
    })
</script>
</body>
</html>

BettingGameApp/templates/login.html
{% extends "layout.html" %}
{% block content %}

<div class="row justify-content-center gy-4">
    <div class="col-8">
        <div class="row justify-content-center">
            <div class="col-2">
                <i class="fas fa-atom fa-5x"></i>
                <h5>Login</h5>
            </div>
        </div>
        <div class="row justify-content-center">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                    <div class="form-floating mb-3">
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid text-dark", id="email1", placeholder="email") }}
                            {{ form.email.label(class="text-dark", for="email1") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg", id="email1", placeholder="email") }}
                            {{ form.email.label(for="email1") }}
                        {% endif %}
                    </div>
                    <div class="form-floating mb-3">
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid", id="password1", placeholder="password") }}
                            {{ form.password.label(for="password1") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg", id="password1", placeholder="password") }}
                            {{ form.password.label(for="password1") }}
                        {% endif %}
                    </div>
                <div class="row">
                    <div class="col-10">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <small class="text-muted">
                            Not a user? <a href="{{ url_for('users.register') }}">Register here.</a>
                        </small>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

BettingGameApp/templates/place_bet.html
{% extends "layout.html" %}
{% block content %}
<h1>PLACE BET PAGE</h1>

<div class="row justify-content-center">
    <div class="col">
        <div class="card text-center">
            <h8 class="card-header">
                Status
            </h8>
            <div class="card-body">
                <span class="badge bg-primary">{{ game_data['status'] }}</span>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card text-center">
            <h8 class="card-header">
                Manager
            </h8>
            <div class="card-body">
                <span class="badge bg-primary text-truncate" data-bs-toggle="popover" data-bs-trigger="hover focus" title="Manager Address" data-bs-content="{{ game_data['manager'] }}">
                    {{ game_data['manager'] }}
                </span>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card text-center">
            <h8 class="card-header">
                Status
            </h8>
            <div class="card-body">
                <span class="badge bg-primary">{{ game_data['bet_min'] }}</span>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card text-center">
            <h8 class="card-header">
                Status
            </h8>
            <div class="card-body">
                <span class="badge bg-primary">0 - {{ game_data['val_range'] }}</span>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card text-center">
            <h8 class="card-header">
                Status
            </h8>
            <div class="card-body">
                <span class="badge bg-primary">{{ game_data['total_pool'] }}</span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-4">
        <div class="card w-75 p-3">
            <h5 class="card-header">Place Bet</h5>
            <div class="card-body">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.game_id.label(class="form-control-label", for="game_id") }}

                        {% if form.game_id.errors %}
                        {{ form.game_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.game_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                            {{ form.game_id(class="form-control form-control-lg", for="game_id") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.prediction.label(class="form-control-label", for="prediction") }}

                        {% if form.prediction.errors %}
                        {{ form.prediction(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.prediction.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                            {{ form.prediction(class="form-control form-control-lg", for="prediction") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.bet_amount.label(class="form-control-label", for="bet_amount") }}

                        {% if form.bet_amount.errors %}
                        {{ form.bet_amount(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.bet_amount.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                            {{ form.bet_amount(class="form-control form-control-lg", for="bet_amount") }}
                        {% endif %}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-8">
        <table class="table table-hover w-75">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Bet Maker</th>
                    <th scope="col">Bet Amount</th>
                    <th scope="col">Prediction</th>
                </tr>
            </thead>
            <tbody>
                {% if bet_data %}
                    {% for b in bet_data.keys() %}
                    <tr>
                        <th scope="row">{{ b + 1}}</th>
                        <td>{{ bet_data[b]['bet_maker'] }}</td>
                        <td>{{ bet_data[b]['bet_amount'] }}</td>
                        <td>{{ bet_data[b]['prediction'] }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <th scope="row">1</th>
                        <td colspan="3"> NO DATA AVAILABLE</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

BettingGameApp/templates/profile.html
{% extends "layout.html" %}
{% block content %}
<h1>PROFILE PAGE</h1>
{% endblock content %}